"""empty message

Revision ID: 52f4717574e8
Revises: 4801900ac6dc
Create Date: 2021-03-19 20:01:58.937784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f4717574e8'
down_revision = '4801900ac6dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'title')
    # ### end Alembic commands ###
